version: '3.7'
services:
  jest-api:
    build: .
    ports:
      - "3333:3333"
    command: yarn start

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: housi
    ports:
      - "27017:27017"
    volumes:
      - /home/Docker/Volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge